CREATE TABLE IF NOT EXISTS products(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    price BIGINT NOT NULL,
    image text,
    item integer NOT NULL UNIQUE
);

SELECT * FROM products;
