CREATE TABLE IF NOT EXISTS products(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL CHECK (name <> ''),
    price BIGINT NOT NULL,
    image text,
    item integer NOT NULL UNIQUE,
    status BOOLEAN DEFAULT false
);

insert into products values
    (1, 'Detodito', 1500, 'imagen1', 12);

SELECT * FROM products;
