CREATE TABLE IF NOT EXISTS products(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL CHECK (name <> ''),
    price BIGINT NOT NULL,
    image text,
    item integer NOT NULL UNIQUE,
    status BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS vendings(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL CHECK (name <> ''),
    machine_id TEXT NOT NULL UNIQUE CHECK (name <> ''),
    status BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS users(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text NOT NULL CHECK (username <> ''),
    email text NOT NULL UNIQUE,
    password text NOT NULL,
    status BOOLEAN DEFAULT true
);

-- insert into products values
--     (1, 'Detodito', 1500, 'imagen1', 12);

SELECT * FROM products;
